name: wikikamus
description: "An app for Wikikamus, the wiktionaries of local languages in Indonesia"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_dotenv: ^6.0.0
  flutter_appauth: ^11.0.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  easy_localization: ^3.0.8
  google_fonts: ^6.3.2
  share_plus: ^12.0.0
  url_launcher: ^6.3.2
  flutter_widget_from_html: ^0.17.1
  http: ^1.5.0
#  html: ^0.15.6
#  flutter_html: ^3.0.0
  beautiful_soup_dart: ^0.3.0
  html_character_entities: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - wikikamus.env
    - assets/images/
    - assets/images/nias/
    - assets/translations/
    - assets/translations/bew.json
    - assets/translations/bjn.json
    - assets/translations/btm.json
    - assets/translations/en.json
    - assets/translations/gor.json
    - assets/translations/id.json
    - assets/translations/jv.json
    - assets/translations/mad.json
    - assets/translations/min.json
    - assets/translations/ms.json
    - assets/translations/nia.json
    - assets/translations/su.json
